//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION_MEDICA
    {
        public string USUARIO_RUT { get; set; }
        public string MEDICO_RUT_MEDICO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string LUGAR { get; set; }
        public decimal EXAMEN_ID_EVALUACION { get; set; }
        public string DIAGNOSTICO { get; set; }
        public decimal ID_ATENCION { get; set; }
    
        public virtual EXAMEN EXAMEN { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
