//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo3
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.EV_EMP = new HashSet<EV_EMP>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public string RUT_EMPRESA { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string ESTADO { get; set; }
        public string CONTRASEÑA { get; set; }
    
        public virtual ICollection<EV_EMP> EV_EMP { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
