//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo3
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_CAP
    {
        public string USUARIO_RUT { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal CAPACITACION_ID { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual CAPACITACION CAPACITACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
