//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEmpresa", Namespace="http://tempuri.org/", ItemName="empresa")]
    [System.SerializableAttribute()]
    public class ArrayOfEmpresa : System.Collections.Generic.List<web.ServiceReference1.empresa> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="empresa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rut_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_empresaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rut_empresa {
            get {
                return this.rut_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.rut_empresaField, value) != true)) {
                    this.rut_empresaField = value;
                    this.RaisePropertyChanged("rut_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre_empresa {
            get {
                return this.nombre_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_empresaField, value) != true)) {
                    this.nombre_empresaField = value;
                    this.RaisePropertyChanged("nombre_empresa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCap_tipo", Namespace="http://tempuri.org/", ItemName="cap_tipo")]
    [System.SerializableAttribute()]
    public class ArrayOfCap_tipo : System.Collections.Generic.List<web.ServiceReference1.cap_tipo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cap_tipo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class cap_tipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCategoria", Namespace="http://tempuri.org/", ItemName="categoria")]
    [System.SerializableAttribute()]
    public class ArrayOfCategoria : System.Collections.Generic.List<web.ServiceReference1.categoria> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="categoria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        private int idTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int idTipo {
            get {
                return this.idTipoField;
            }
            set {
                if ((this.idTipoField.Equals(value) != true)) {
                    this.idTipoField = value;
                    this.RaisePropertyChanged("idTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfArea", Namespace="http://tempuri.org/", ItemName="area")]
    [System.SerializableAttribute()]
    public class ArrayOfArea : System.Collections.Generic.List<web.ServiceReference1.area> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="area", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class area : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_areaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre_area {
            get {
                return this.nombre_areaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_areaField, value) != true)) {
                    this.nombre_areaField = value;
                    this.RaisePropertyChanged("nombre_area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCapacitacion", Namespace="http://tempuri.org/", ItemName="capacitacion")]
    [System.SerializableAttribute()]
    public class ArrayOfCapacitacion : System.Collections.Generic.List<web.ServiceReference1.capacitacion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="capacitacion", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class capacitacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpositorField;
        
        private int AsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Rut_empresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_capField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tema {
            get {
                return this.TemaField;
            }
            set {
                if ((object.ReferenceEquals(this.TemaField, value) != true)) {
                    this.TemaField = value;
                    this.RaisePropertyChanged("Tema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Expositor {
            get {
                return this.ExpositorField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpositorField, value) != true)) {
                    this.ExpositorField = value;
                    this.RaisePropertyChanged("Expositor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Asistencia {
            get {
                return this.AsistenciaField;
            }
            set {
                if ((this.AsistenciaField.Equals(value) != true)) {
                    this.AsistenciaField = value;
                    this.RaisePropertyChanged("Asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Rut_empresa {
            get {
                return this.Rut_empresaField;
            }
            set {
                if ((object.ReferenceEquals(this.Rut_empresaField, value) != true)) {
                    this.Rut_empresaField = value;
                    this.RaisePropertyChanged("Rut_empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Tipo_cap {
            get {
                return this.Tipo_capField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_capField, value) != true)) {
                    this.Tipo_capField = value;
                    this.RaisePropertyChanged("Tipo_cap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.wsa1Soap")]
    public interface wsa1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        web.ServiceReference1.HelloWorldResponse HelloWorld(web.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.HelloWorldResponse> HelloWorldAsync(web.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        web.ServiceReference1.ValidarResponse Validar(web.ServiceReference1.ValidarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validar", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.ValidarResponse> ValidarAsync(web.ServiceReference1.ValidarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevuelveTipo", ReplyAction="*")]
        web.ServiceReference1.DevuelveTipoResponse DevuelveTipo(web.ServiceReference1.DevuelveTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevuelveTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.DevuelveTipoResponse> DevuelveTipoAsync(web.ServiceReference1.DevuelveTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetlistarEmpresaListResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetlistarEmpresaList", ReplyAction="*")]
        web.ServiceReference1.GetlistarEmpresaListResponse GetlistarEmpresaList(web.ServiceReference1.GetlistarEmpresaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetlistarEmpresaList", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.GetlistarEmpresaListResponse> GetlistarEmpresaListAsync(web.ServiceReference1.GetlistarEmpresaListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetListarTipoCapResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListarTipoCap", ReplyAction="*")]
        web.ServiceReference1.GetListarTipoCapResponse GetListarTipoCap(web.ServiceReference1.GetListarTipoCapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListarTipoCap", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.GetListarTipoCapResponse> GetListarTipoCapAsync(web.ServiceReference1.GetListarTipoCapRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Item del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarCategoria", ReplyAction="*")]
        web.ServiceReference1.GuardarCategoriaResponse GuardarCategoria(web.ServiceReference1.GuardarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.GuardarCategoriaResponse> GuardarCategoriaAsync(web.ServiceReference1.GuardarCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarCategoriasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCategorias", ReplyAction="*")]
        web.ServiceReference1.ListarCategoriasResponse ListarCategorias(web.ServiceReference1.ListarCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.ListarCategoriasResponse> ListarCategoriasAsync(web.ServiceReference1.ListarCategoriasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarCategoriasXtipoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCategoriasXtipo", ReplyAction="*")]
        web.ServiceReference1.ListarCategoriasXtipoResponse ListarCategoriasXtipo(web.ServiceReference1.ListarCategoriasXtipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCategoriasXtipo", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.ListarCategoriasXtipoResponse> ListarCategoriasXtipoAsync(web.ServiceReference1.ListarCategoriasXtipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento area del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarCapacitacion", ReplyAction="*")]
        web.ServiceReference1.GuardarCapacitacionResponse GuardarCapacitacion(web.ServiceReference1.GuardarCapacitacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarCapacitacion", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.GuardarCapacitacionResponse> GuardarCapacitacionAsync(web.ServiceReference1.GuardarCapacitacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarAreaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarArea", ReplyAction="*")]
        web.ServiceReference1.listarAreaResponse listarArea(web.ServiceReference1.listarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarArea", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.listarAreaResponse> listarAreaAsync(web.ServiceReference1.listarAreaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarCapacitacionesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCapacitaciones", ReplyAction="*")]
        web.ServiceReference1.ListarCapacitacionesResponse ListarCapacitaciones(web.ServiceReference1.ListarCapacitacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCapacitaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<web.ServiceReference1.ListarCapacitacionesResponse> ListarCapacitacionesAsync(web.ServiceReference1.ListarCapacitacionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(web.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(web.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ValidarRequestBody Body;
        
        public ValidarRequest() {
        }
        
        public ValidarRequest(web.ServiceReference1.ValidarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipo;
        
        public ValidarRequestBody() {
        }
        
        public ValidarRequestBody(string rut, string pass, string tipo) {
            this.rut = rut;
            this.pass = pass;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ValidarResponseBody Body;
        
        public ValidarResponse() {
        }
        
        public ValidarResponse(web.ServiceReference1.ValidarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarResult;
        
        public ValidarResponseBody() {
        }
        
        public ValidarResponseBody(string ValidarResult) {
            this.ValidarResult = ValidarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevuelveTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevuelveTipo", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.DevuelveTipoRequestBody Body;
        
        public DevuelveTipoRequest() {
        }
        
        public DevuelveTipoRequest(web.ServiceReference1.DevuelveTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevuelveTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipo;
        
        public DevuelveTipoRequestBody() {
        }
        
        public DevuelveTipoRequestBody(string rut, string tipo) {
            this.rut = rut;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevuelveTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevuelveTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.DevuelveTipoResponseBody Body;
        
        public DevuelveTipoResponse() {
        }
        
        public DevuelveTipoResponse(web.ServiceReference1.DevuelveTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevuelveTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevuelveTipoResult;
        
        public DevuelveTipoResponseBody() {
        }
        
        public DevuelveTipoResponseBody(string DevuelveTipoResult) {
            this.DevuelveTipoResult = DevuelveTipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlistarEmpresaListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlistarEmpresaList", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GetlistarEmpresaListRequestBody Body;
        
        public GetlistarEmpresaListRequest() {
        }
        
        public GetlistarEmpresaListRequest(web.ServiceReference1.GetlistarEmpresaListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetlistarEmpresaListRequestBody {
        
        public GetlistarEmpresaListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetlistarEmpresaListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetlistarEmpresaListResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GetlistarEmpresaListResponseBody Body;
        
        public GetlistarEmpresaListResponse() {
        }
        
        public GetlistarEmpresaListResponse(web.ServiceReference1.GetlistarEmpresaListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetlistarEmpresaListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.ServiceReference1.ArrayOfEmpresa GetlistarEmpresaListResult;
        
        public GetlistarEmpresaListResponseBody() {
        }
        
        public GetlistarEmpresaListResponseBody(web.ServiceReference1.ArrayOfEmpresa GetlistarEmpresaListResult) {
            this.GetlistarEmpresaListResult = GetlistarEmpresaListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListarTipoCapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListarTipoCap", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GetListarTipoCapRequestBody Body;
        
        public GetListarTipoCapRequest() {
        }
        
        public GetListarTipoCapRequest(web.ServiceReference1.GetListarTipoCapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListarTipoCapRequestBody {
        
        public GetListarTipoCapRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListarTipoCapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListarTipoCapResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GetListarTipoCapResponseBody Body;
        
        public GetListarTipoCapResponse() {
        }
        
        public GetListarTipoCapResponse(web.ServiceReference1.GetListarTipoCapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListarTipoCapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.ServiceReference1.ArrayOfCap_tipo GetListarTipoCapResult;
        
        public GetListarTipoCapResponseBody() {
        }
        
        public GetListarTipoCapResponseBody(web.ServiceReference1.ArrayOfCap_tipo GetListarTipoCapResult) {
            this.GetListarTipoCapResult = GetListarTipoCapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GuardarCategoriaRequestBody Body;
        
        public GuardarCategoriaRequest() {
        }
        
        public GuardarCategoriaRequest(web.ServiceReference1.GuardarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Item;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        public GuardarCategoriaRequestBody() {
        }
        
        public GuardarCategoriaRequestBody(string Item, int id) {
            this.Item = Item;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GuardarCategoriaResponseBody Body;
        
        public GuardarCategoriaResponse() {
        }
        
        public GuardarCategoriaResponse(web.ServiceReference1.GuardarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GuardarCategoriaResult;
        
        public GuardarCategoriaResponseBody() {
        }
        
        public GuardarCategoriaResponseBody(bool GuardarCategoriaResult) {
            this.GuardarCategoriaResult = GuardarCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCategorias", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ListarCategoriasRequestBody Body;
        
        public ListarCategoriasRequest() {
        }
        
        public ListarCategoriasRequest(web.ServiceReference1.ListarCategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarCategoriasRequestBody {
        
        public ListarCategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ListarCategoriasResponseBody Body;
        
        public ListarCategoriasResponse() {
        }
        
        public ListarCategoriasResponse(web.ServiceReference1.ListarCategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarCategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.ServiceReference1.ArrayOfCategoria ListarCategoriasResult;
        
        public ListarCategoriasResponseBody() {
        }
        
        public ListarCategoriasResponseBody(web.ServiceReference1.ArrayOfCategoria ListarCategoriasResult) {
            this.ListarCategoriasResult = ListarCategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCategoriasXtipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCategoriasXtipo", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ListarCategoriasXtipoRequestBody Body;
        
        public ListarCategoriasXtipoRequest() {
        }
        
        public ListarCategoriasXtipoRequest(web.ServiceReference1.ListarCategoriasXtipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarCategoriasXtipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ListarCategoriasXtipoRequestBody() {
        }
        
        public ListarCategoriasXtipoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCategoriasXtipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCategoriasXtipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ListarCategoriasXtipoResponseBody Body;
        
        public ListarCategoriasXtipoResponse() {
        }
        
        public ListarCategoriasXtipoResponse(web.ServiceReference1.ListarCategoriasXtipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarCategoriasXtipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.ServiceReference1.ArrayOfCategoria ListarCategoriasXtipoResult;
        
        public ListarCategoriasXtipoResponseBody() {
        }
        
        public ListarCategoriasXtipoResponseBody(web.ServiceReference1.ArrayOfCategoria ListarCategoriasXtipoResult) {
            this.ListarCategoriasXtipoResult = ListarCategoriasXtipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarCapacitacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarCapacitacion", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GuardarCapacitacionRequestBody Body;
        
        public GuardarCapacitacionRequest() {
        }
        
        public GuardarCapacitacionRequest(web.ServiceReference1.GuardarCapacitacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarCapacitacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string area;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string expo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int asisten;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int tipocap;
        
        public GuardarCapacitacionRequestBody() {
        }
        
        public GuardarCapacitacionRequestBody(string area, System.DateTime fecha, string tema, string expo, int asisten, string empresa, int tipocap) {
            this.area = area;
            this.fecha = fecha;
            this.tema = tema;
            this.expo = expo;
            this.asisten = asisten;
            this.empresa = empresa;
            this.tipocap = tipocap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarCapacitacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarCapacitacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.GuardarCapacitacionResponseBody Body;
        
        public GuardarCapacitacionResponse() {
        }
        
        public GuardarCapacitacionResponse(web.ServiceReference1.GuardarCapacitacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarCapacitacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GuardarCapacitacionResult;
        
        public GuardarCapacitacionResponseBody() {
        }
        
        public GuardarCapacitacionResponseBody(bool GuardarCapacitacionResult) {
            this.GuardarCapacitacionResult = GuardarCapacitacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarArea", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.listarAreaRequestBody Body;
        
        public listarAreaRequest() {
        }
        
        public listarAreaRequest(web.ServiceReference1.listarAreaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarAreaRequestBody {
        
        public listarAreaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarAreaResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.listarAreaResponseBody Body;
        
        public listarAreaResponse() {
        }
        
        public listarAreaResponse(web.ServiceReference1.listarAreaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarAreaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.ServiceReference1.ArrayOfArea listarAreaResult;
        
        public listarAreaResponseBody() {
        }
        
        public listarAreaResponseBody(web.ServiceReference1.ArrayOfArea listarAreaResult) {
            this.listarAreaResult = listarAreaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCapacitacionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCapacitaciones", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ListarCapacitacionesRequestBody Body;
        
        public ListarCapacitacionesRequest() {
        }
        
        public ListarCapacitacionesRequest(web.ServiceReference1.ListarCapacitacionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarCapacitacionesRequestBody {
        
        public ListarCapacitacionesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarCapacitacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarCapacitacionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public web.ServiceReference1.ListarCapacitacionesResponseBody Body;
        
        public ListarCapacitacionesResponse() {
        }
        
        public ListarCapacitacionesResponse(web.ServiceReference1.ListarCapacitacionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarCapacitacionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public web.ServiceReference1.ArrayOfCapacitacion ListarCapacitacionesResult;
        
        public ListarCapacitacionesResponseBody() {
        }
        
        public ListarCapacitacionesResponseBody(web.ServiceReference1.ArrayOfCapacitacion ListarCapacitacionesResult) {
            this.ListarCapacitacionesResult = ListarCapacitacionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsa1SoapChannel : web.ServiceReference1.wsa1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsa1SoapClient : System.ServiceModel.ClientBase<web.ServiceReference1.wsa1Soap>, web.ServiceReference1.wsa1Soap {
        
        public wsa1SoapClient() {
        }
        
        public wsa1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsa1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsa1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsa1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.HelloWorldResponse web.ServiceReference1.wsa1Soap.HelloWorld(web.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            web.ServiceReference1.HelloWorldRequest inValue = new web.ServiceReference1.HelloWorldRequest();
            inValue.Body = new web.ServiceReference1.HelloWorldRequestBody();
            web.ServiceReference1.HelloWorldResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.HelloWorldResponse> web.ServiceReference1.wsa1Soap.HelloWorldAsync(web.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            web.ServiceReference1.HelloWorldRequest inValue = new web.ServiceReference1.HelloWorldRequest();
            inValue.Body = new web.ServiceReference1.HelloWorldRequestBody();
            return ((web.ServiceReference1.wsa1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.ValidarResponse web.ServiceReference1.wsa1Soap.Validar(web.ServiceReference1.ValidarRequest request) {
            return base.Channel.Validar(request);
        }
        
        public string Validar(string rut, string pass, string tipo) {
            web.ServiceReference1.ValidarRequest inValue = new web.ServiceReference1.ValidarRequest();
            inValue.Body = new web.ServiceReference1.ValidarRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.pass = pass;
            inValue.Body.tipo = tipo;
            web.ServiceReference1.ValidarResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).Validar(inValue);
            return retVal.Body.ValidarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.ValidarResponse> web.ServiceReference1.wsa1Soap.ValidarAsync(web.ServiceReference1.ValidarRequest request) {
            return base.Channel.ValidarAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.ValidarResponse> ValidarAsync(string rut, string pass, string tipo) {
            web.ServiceReference1.ValidarRequest inValue = new web.ServiceReference1.ValidarRequest();
            inValue.Body = new web.ServiceReference1.ValidarRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.pass = pass;
            inValue.Body.tipo = tipo;
            return ((web.ServiceReference1.wsa1Soap)(this)).ValidarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.DevuelveTipoResponse web.ServiceReference1.wsa1Soap.DevuelveTipo(web.ServiceReference1.DevuelveTipoRequest request) {
            return base.Channel.DevuelveTipo(request);
        }
        
        public string DevuelveTipo(string rut, string tipo) {
            web.ServiceReference1.DevuelveTipoRequest inValue = new web.ServiceReference1.DevuelveTipoRequest();
            inValue.Body = new web.ServiceReference1.DevuelveTipoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.tipo = tipo;
            web.ServiceReference1.DevuelveTipoResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).DevuelveTipo(inValue);
            return retVal.Body.DevuelveTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.DevuelveTipoResponse> web.ServiceReference1.wsa1Soap.DevuelveTipoAsync(web.ServiceReference1.DevuelveTipoRequest request) {
            return base.Channel.DevuelveTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.DevuelveTipoResponse> DevuelveTipoAsync(string rut, string tipo) {
            web.ServiceReference1.DevuelveTipoRequest inValue = new web.ServiceReference1.DevuelveTipoRequest();
            inValue.Body = new web.ServiceReference1.DevuelveTipoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.tipo = tipo;
            return ((web.ServiceReference1.wsa1Soap)(this)).DevuelveTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.GetlistarEmpresaListResponse web.ServiceReference1.wsa1Soap.GetlistarEmpresaList(web.ServiceReference1.GetlistarEmpresaListRequest request) {
            return base.Channel.GetlistarEmpresaList(request);
        }
        
        public web.ServiceReference1.ArrayOfEmpresa GetlistarEmpresaList() {
            web.ServiceReference1.GetlistarEmpresaListRequest inValue = new web.ServiceReference1.GetlistarEmpresaListRequest();
            inValue.Body = new web.ServiceReference1.GetlistarEmpresaListRequestBody();
            web.ServiceReference1.GetlistarEmpresaListResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).GetlistarEmpresaList(inValue);
            return retVal.Body.GetlistarEmpresaListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.GetlistarEmpresaListResponse> web.ServiceReference1.wsa1Soap.GetlistarEmpresaListAsync(web.ServiceReference1.GetlistarEmpresaListRequest request) {
            return base.Channel.GetlistarEmpresaListAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.GetlistarEmpresaListResponse> GetlistarEmpresaListAsync() {
            web.ServiceReference1.GetlistarEmpresaListRequest inValue = new web.ServiceReference1.GetlistarEmpresaListRequest();
            inValue.Body = new web.ServiceReference1.GetlistarEmpresaListRequestBody();
            return ((web.ServiceReference1.wsa1Soap)(this)).GetlistarEmpresaListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.GetListarTipoCapResponse web.ServiceReference1.wsa1Soap.GetListarTipoCap(web.ServiceReference1.GetListarTipoCapRequest request) {
            return base.Channel.GetListarTipoCap(request);
        }
        
        public web.ServiceReference1.ArrayOfCap_tipo GetListarTipoCap() {
            web.ServiceReference1.GetListarTipoCapRequest inValue = new web.ServiceReference1.GetListarTipoCapRequest();
            inValue.Body = new web.ServiceReference1.GetListarTipoCapRequestBody();
            web.ServiceReference1.GetListarTipoCapResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).GetListarTipoCap(inValue);
            return retVal.Body.GetListarTipoCapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.GetListarTipoCapResponse> web.ServiceReference1.wsa1Soap.GetListarTipoCapAsync(web.ServiceReference1.GetListarTipoCapRequest request) {
            return base.Channel.GetListarTipoCapAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.GetListarTipoCapResponse> GetListarTipoCapAsync() {
            web.ServiceReference1.GetListarTipoCapRequest inValue = new web.ServiceReference1.GetListarTipoCapRequest();
            inValue.Body = new web.ServiceReference1.GetListarTipoCapRequestBody();
            return ((web.ServiceReference1.wsa1Soap)(this)).GetListarTipoCapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.GuardarCategoriaResponse web.ServiceReference1.wsa1Soap.GuardarCategoria(web.ServiceReference1.GuardarCategoriaRequest request) {
            return base.Channel.GuardarCategoria(request);
        }
        
        public bool GuardarCategoria(string Item, int id) {
            web.ServiceReference1.GuardarCategoriaRequest inValue = new web.ServiceReference1.GuardarCategoriaRequest();
            inValue.Body = new web.ServiceReference1.GuardarCategoriaRequestBody();
            inValue.Body.Item = Item;
            inValue.Body.id = id;
            web.ServiceReference1.GuardarCategoriaResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).GuardarCategoria(inValue);
            return retVal.Body.GuardarCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.GuardarCategoriaResponse> web.ServiceReference1.wsa1Soap.GuardarCategoriaAsync(web.ServiceReference1.GuardarCategoriaRequest request) {
            return base.Channel.GuardarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.GuardarCategoriaResponse> GuardarCategoriaAsync(string Item, int id) {
            web.ServiceReference1.GuardarCategoriaRequest inValue = new web.ServiceReference1.GuardarCategoriaRequest();
            inValue.Body = new web.ServiceReference1.GuardarCategoriaRequestBody();
            inValue.Body.Item = Item;
            inValue.Body.id = id;
            return ((web.ServiceReference1.wsa1Soap)(this)).GuardarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.ListarCategoriasResponse web.ServiceReference1.wsa1Soap.ListarCategorias(web.ServiceReference1.ListarCategoriasRequest request) {
            return base.Channel.ListarCategorias(request);
        }
        
        public web.ServiceReference1.ArrayOfCategoria ListarCategorias() {
            web.ServiceReference1.ListarCategoriasRequest inValue = new web.ServiceReference1.ListarCategoriasRequest();
            inValue.Body = new web.ServiceReference1.ListarCategoriasRequestBody();
            web.ServiceReference1.ListarCategoriasResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).ListarCategorias(inValue);
            return retVal.Body.ListarCategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.ListarCategoriasResponse> web.ServiceReference1.wsa1Soap.ListarCategoriasAsync(web.ServiceReference1.ListarCategoriasRequest request) {
            return base.Channel.ListarCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.ListarCategoriasResponse> ListarCategoriasAsync() {
            web.ServiceReference1.ListarCategoriasRequest inValue = new web.ServiceReference1.ListarCategoriasRequest();
            inValue.Body = new web.ServiceReference1.ListarCategoriasRequestBody();
            return ((web.ServiceReference1.wsa1Soap)(this)).ListarCategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.ListarCategoriasXtipoResponse web.ServiceReference1.wsa1Soap.ListarCategoriasXtipo(web.ServiceReference1.ListarCategoriasXtipoRequest request) {
            return base.Channel.ListarCategoriasXtipo(request);
        }
        
        public web.ServiceReference1.ArrayOfCategoria ListarCategoriasXtipo(int id) {
            web.ServiceReference1.ListarCategoriasXtipoRequest inValue = new web.ServiceReference1.ListarCategoriasXtipoRequest();
            inValue.Body = new web.ServiceReference1.ListarCategoriasXtipoRequestBody();
            inValue.Body.id = id;
            web.ServiceReference1.ListarCategoriasXtipoResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).ListarCategoriasXtipo(inValue);
            return retVal.Body.ListarCategoriasXtipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.ListarCategoriasXtipoResponse> web.ServiceReference1.wsa1Soap.ListarCategoriasXtipoAsync(web.ServiceReference1.ListarCategoriasXtipoRequest request) {
            return base.Channel.ListarCategoriasXtipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.ListarCategoriasXtipoResponse> ListarCategoriasXtipoAsync(int id) {
            web.ServiceReference1.ListarCategoriasXtipoRequest inValue = new web.ServiceReference1.ListarCategoriasXtipoRequest();
            inValue.Body = new web.ServiceReference1.ListarCategoriasXtipoRequestBody();
            inValue.Body.id = id;
            return ((web.ServiceReference1.wsa1Soap)(this)).ListarCategoriasXtipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.GuardarCapacitacionResponse web.ServiceReference1.wsa1Soap.GuardarCapacitacion(web.ServiceReference1.GuardarCapacitacionRequest request) {
            return base.Channel.GuardarCapacitacion(request);
        }
        
        public bool GuardarCapacitacion(string area, System.DateTime fecha, string tema, string expo, int asisten, string empresa, int tipocap) {
            web.ServiceReference1.GuardarCapacitacionRequest inValue = new web.ServiceReference1.GuardarCapacitacionRequest();
            inValue.Body = new web.ServiceReference1.GuardarCapacitacionRequestBody();
            inValue.Body.area = area;
            inValue.Body.fecha = fecha;
            inValue.Body.tema = tema;
            inValue.Body.expo = expo;
            inValue.Body.asisten = asisten;
            inValue.Body.empresa = empresa;
            inValue.Body.tipocap = tipocap;
            web.ServiceReference1.GuardarCapacitacionResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).GuardarCapacitacion(inValue);
            return retVal.Body.GuardarCapacitacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.GuardarCapacitacionResponse> web.ServiceReference1.wsa1Soap.GuardarCapacitacionAsync(web.ServiceReference1.GuardarCapacitacionRequest request) {
            return base.Channel.GuardarCapacitacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.GuardarCapacitacionResponse> GuardarCapacitacionAsync(string area, System.DateTime fecha, string tema, string expo, int asisten, string empresa, int tipocap) {
            web.ServiceReference1.GuardarCapacitacionRequest inValue = new web.ServiceReference1.GuardarCapacitacionRequest();
            inValue.Body = new web.ServiceReference1.GuardarCapacitacionRequestBody();
            inValue.Body.area = area;
            inValue.Body.fecha = fecha;
            inValue.Body.tema = tema;
            inValue.Body.expo = expo;
            inValue.Body.asisten = asisten;
            inValue.Body.empresa = empresa;
            inValue.Body.tipocap = tipocap;
            return ((web.ServiceReference1.wsa1Soap)(this)).GuardarCapacitacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.listarAreaResponse web.ServiceReference1.wsa1Soap.listarArea(web.ServiceReference1.listarAreaRequest request) {
            return base.Channel.listarArea(request);
        }
        
        public web.ServiceReference1.ArrayOfArea listarArea() {
            web.ServiceReference1.listarAreaRequest inValue = new web.ServiceReference1.listarAreaRequest();
            inValue.Body = new web.ServiceReference1.listarAreaRequestBody();
            web.ServiceReference1.listarAreaResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).listarArea(inValue);
            return retVal.Body.listarAreaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.listarAreaResponse> web.ServiceReference1.wsa1Soap.listarAreaAsync(web.ServiceReference1.listarAreaRequest request) {
            return base.Channel.listarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.listarAreaResponse> listarAreaAsync() {
            web.ServiceReference1.listarAreaRequest inValue = new web.ServiceReference1.listarAreaRequest();
            inValue.Body = new web.ServiceReference1.listarAreaRequestBody();
            return ((web.ServiceReference1.wsa1Soap)(this)).listarAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        web.ServiceReference1.ListarCapacitacionesResponse web.ServiceReference1.wsa1Soap.ListarCapacitaciones(web.ServiceReference1.ListarCapacitacionesRequest request) {
            return base.Channel.ListarCapacitaciones(request);
        }
        
        public web.ServiceReference1.ArrayOfCapacitacion ListarCapacitaciones() {
            web.ServiceReference1.ListarCapacitacionesRequest inValue = new web.ServiceReference1.ListarCapacitacionesRequest();
            inValue.Body = new web.ServiceReference1.ListarCapacitacionesRequestBody();
            web.ServiceReference1.ListarCapacitacionesResponse retVal = ((web.ServiceReference1.wsa1Soap)(this)).ListarCapacitaciones(inValue);
            return retVal.Body.ListarCapacitacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<web.ServiceReference1.ListarCapacitacionesResponse> web.ServiceReference1.wsa1Soap.ListarCapacitacionesAsync(web.ServiceReference1.ListarCapacitacionesRequest request) {
            return base.Channel.ListarCapacitacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<web.ServiceReference1.ListarCapacitacionesResponse> ListarCapacitacionesAsync() {
            web.ServiceReference1.ListarCapacitacionesRequest inValue = new web.ServiceReference1.ListarCapacitacionesRequest();
            inValue.Body = new web.ServiceReference1.ListarCapacitacionesRequestBody();
            return ((web.ServiceReference1.wsa1Soap)(this)).ListarCapacitacionesAsync(inValue);
        }
    }
}
