//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Model", "US_CAP_CAPACITACION_FK", "CAPACITACION", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.CAPACITACION), "US_CAP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.US_CAP), true)]
[assembly: EdmRelationshipAttribute("Model", "EV_EMP_EMPRESA_FK", "EMPRESA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.EMPRESA), "EV_EMP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.EV_EMP), true)]
[assembly: EdmRelationshipAttribute("Model", "USUARIO_EMPRESA_FK", "EMPRESA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.EMPRESA), "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.USUARIO), true)]
[assembly: EdmRelationshipAttribute("Model", "EV_EMP_EVALUACION_FK", "EVALUACION", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.EVALUACION), "EV_EMP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.EV_EMP), true)]
[assembly: EdmRelationshipAttribute("Model", "ATENCION_MEDICA_EXAMEN_FK", "EXAMEN", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.EXAMEN), "ATENCION_MEDICA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.ATENCION_MEDICA), true)]
[assembly: EdmRelationshipAttribute("Model", "ATENCION_MEDICA_MEDICO_FK", "MEDICO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.MEDICO), "ATENCION_MEDICA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.ATENCION_MEDICA), true)]
[assembly: EdmRelationshipAttribute("Model", "ATENCION_MEDICA_USUARIO_FK", "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.USUARIO), "ATENCION_MEDICA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.ATENCION_MEDICA), true)]
[assembly: EdmRelationshipAttribute("Model", "US_CAP_USUARIO_FK", "USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Modelo.USUARIO), "US_CAP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Modelo.US_CAP), true)]

#endregion

namespace Modelo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Entities usando la cadena de conexión encontrada en la sección 'Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CAPACITACION> CAPACITACION
        {
            get
            {
                if ((_CAPACITACION == null))
                {
                    _CAPACITACION = base.CreateObjectSet<CAPACITACION>("CAPACITACION");
                }
                return _CAPACITACION;
            }
        }
        private ObjectSet<CAPACITACION> _CAPACITACION;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EMPRESA> EMPRESA
        {
            get
            {
                if ((_EMPRESA == null))
                {
                    _EMPRESA = base.CreateObjectSet<EMPRESA>("EMPRESA");
                }
                return _EMPRESA;
            }
        }
        private ObjectSet<EMPRESA> _EMPRESA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EV_EMP> EV_EMP
        {
            get
            {
                if ((_EV_EMP == null))
                {
                    _EV_EMP = base.CreateObjectSet<EV_EMP>("EV_EMP");
                }
                return _EV_EMP;
            }
        }
        private ObjectSet<EV_EMP> _EV_EMP;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EVALUACION> EVALUACION
        {
            get
            {
                if ((_EVALUACION == null))
                {
                    _EVALUACION = base.CreateObjectSet<EVALUACION>("EVALUACION");
                }
                return _EVALUACION;
            }
        }
        private ObjectSet<EVALUACION> _EVALUACION;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EXAMEN> EXAMEN
        {
            get
            {
                if ((_EXAMEN == null))
                {
                    _EXAMEN = base.CreateObjectSet<EXAMEN>("EXAMEN");
                }
                return _EXAMEN;
            }
        }
        private ObjectSet<EXAMEN> _EXAMEN;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<MEDICO> MEDICO
        {
            get
            {
                if ((_MEDICO == null))
                {
                    _MEDICO = base.CreateObjectSet<MEDICO>("MEDICO");
                }
                return _MEDICO;
            }
        }
        private ObjectSet<MEDICO> _MEDICO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<USUARIO> USUARIO
        {
            get
            {
                if ((_USUARIO == null))
                {
                    _USUARIO = base.CreateObjectSet<USUARIO>("USUARIO");
                }
                return _USUARIO;
            }
        }
        private ObjectSet<USUARIO> _USUARIO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ATENCION_MEDICA> ATENCION_MEDICA
        {
            get
            {
                if ((_ATENCION_MEDICA == null))
                {
                    _ATENCION_MEDICA = base.CreateObjectSet<ATENCION_MEDICA>("ATENCION_MEDICA");
                }
                return _ATENCION_MEDICA;
            }
        }
        private ObjectSet<ATENCION_MEDICA> _ATENCION_MEDICA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<US_CAP> US_CAP
        {
            get
            {
                if ((_US_CAP == null))
                {
                    _US_CAP = base.CreateObjectSet<US_CAP>("US_CAP");
                }
                return _US_CAP;
            }
        }
        private ObjectSet<US_CAP> _US_CAP;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CAPACITACION. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCAPACITACION(CAPACITACION cAPACITACION)
        {
            base.AddObject("CAPACITACION", cAPACITACION);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EMPRESA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEMPRESA(EMPRESA eMPRESA)
        {
            base.AddObject("EMPRESA", eMPRESA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EV_EMP. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEV_EMP(EV_EMP eV_EMP)
        {
            base.AddObject("EV_EMP", eV_EMP);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EVALUACION. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEVALUACION(EVALUACION eVALUACION)
        {
            base.AddObject("EVALUACION", eVALUACION);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EXAMEN. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEXAMEN(EXAMEN eXAMEN)
        {
            base.AddObject("EXAMEN", eXAMEN);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MEDICO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMEDICO(MEDICO mEDICO)
        {
            base.AddObject("MEDICO", mEDICO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet USUARIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUSUARIO(USUARIO uSUARIO)
        {
            base.AddObject("USUARIO", uSUARIO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ATENCION_MEDICA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToATENCION_MEDICA(ATENCION_MEDICA aTENCION_MEDICA)
        {
            base.AddObject("ATENCION_MEDICA", aTENCION_MEDICA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet US_CAP. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUS_CAP(US_CAP uS_CAP)
        {
            base.AddObject("US_CAP", uS_CAP);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="ATENCION_MEDICA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ATENCION_MEDICA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ATENCION_MEDICA.
        /// </summary>
        /// <param name="uSUARIO_RUT">Valor inicial de la propiedad USUARIO_RUT.</param>
        /// <param name="mEDICO_RUT_MEDICO">Valor inicial de la propiedad MEDICO_RUT_MEDICO.</param>
        /// <param name="fECHA">Valor inicial de la propiedad FECHA.</param>
        /// <param name="lUGAR">Valor inicial de la propiedad LUGAR.</param>
        /// <param name="eXAMEN_ID_EVALUACION">Valor inicial de la propiedad EXAMEN_ID_EVALUACION.</param>
        /// <param name="dIAGNOSTICO">Valor inicial de la propiedad DIAGNOSTICO.</param>
        /// <param name="iD_ATENCION">Valor inicial de la propiedad ID_ATENCION.</param>
        public static ATENCION_MEDICA CreateATENCION_MEDICA(global::System.String uSUARIO_RUT, global::System.String mEDICO_RUT_MEDICO, global::System.DateTime fECHA, global::System.String lUGAR, global::System.Decimal eXAMEN_ID_EVALUACION, global::System.String dIAGNOSTICO, global::System.Decimal iD_ATENCION)
        {
            ATENCION_MEDICA aTENCION_MEDICA = new ATENCION_MEDICA();
            aTENCION_MEDICA.USUARIO_RUT = uSUARIO_RUT;
            aTENCION_MEDICA.MEDICO_RUT_MEDICO = mEDICO_RUT_MEDICO;
            aTENCION_MEDICA.FECHA = fECHA;
            aTENCION_MEDICA.LUGAR = lUGAR;
            aTENCION_MEDICA.EXAMEN_ID_EVALUACION = eXAMEN_ID_EVALUACION;
            aTENCION_MEDICA.DIAGNOSTICO = dIAGNOSTICO;
            aTENCION_MEDICA.ID_ATENCION = iD_ATENCION;
            return aTENCION_MEDICA;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_RUT
        {
            get
            {
                return _USUARIO_RUT;
            }
            set
            {
                if (_USUARIO_RUT != value)
                {
                    OnUSUARIO_RUTChanging(value);
                    ReportPropertyChanging("USUARIO_RUT");
                    _USUARIO_RUT = StructuralObject.SetValidValue(value, false, "USUARIO_RUT");
                    ReportPropertyChanged("USUARIO_RUT");
                    OnUSUARIO_RUTChanged();
                }
            }
        }
        private global::System.String _USUARIO_RUT;
        partial void OnUSUARIO_RUTChanging(global::System.String value);
        partial void OnUSUARIO_RUTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MEDICO_RUT_MEDICO
        {
            get
            {
                return _MEDICO_RUT_MEDICO;
            }
            set
            {
                if (_MEDICO_RUT_MEDICO != value)
                {
                    OnMEDICO_RUT_MEDICOChanging(value);
                    ReportPropertyChanging("MEDICO_RUT_MEDICO");
                    _MEDICO_RUT_MEDICO = StructuralObject.SetValidValue(value, false, "MEDICO_RUT_MEDICO");
                    ReportPropertyChanged("MEDICO_RUT_MEDICO");
                    OnMEDICO_RUT_MEDICOChanged();
                }
            }
        }
        private global::System.String _MEDICO_RUT_MEDICO;
        partial void OnMEDICO_RUT_MEDICOChanging(global::System.String value);
        partial void OnMEDICO_RUT_MEDICOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                if (_FECHA != value)
                {
                    OnFECHAChanging(value);
                    ReportPropertyChanging("FECHA");
                    _FECHA = StructuralObject.SetValidValue(value, "FECHA");
                    ReportPropertyChanged("FECHA");
                    OnFECHAChanged();
                }
            }
        }
        private global::System.DateTime _FECHA;
        partial void OnFECHAChanging(global::System.DateTime value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUGAR
        {
            get
            {
                return _LUGAR;
            }
            set
            {
                if (_LUGAR != value)
                {
                    OnLUGARChanging(value);
                    ReportPropertyChanging("LUGAR");
                    _LUGAR = StructuralObject.SetValidValue(value, false, "LUGAR");
                    ReportPropertyChanged("LUGAR");
                    OnLUGARChanged();
                }
            }
        }
        private global::System.String _LUGAR;
        partial void OnLUGARChanging(global::System.String value);
        partial void OnLUGARChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EXAMEN_ID_EVALUACION
        {
            get
            {
                return _EXAMEN_ID_EVALUACION;
            }
            set
            {
                if (_EXAMEN_ID_EVALUACION != value)
                {
                    OnEXAMEN_ID_EVALUACIONChanging(value);
                    ReportPropertyChanging("EXAMEN_ID_EVALUACION");
                    _EXAMEN_ID_EVALUACION = StructuralObject.SetValidValue(value, "EXAMEN_ID_EVALUACION");
                    ReportPropertyChanged("EXAMEN_ID_EVALUACION");
                    OnEXAMEN_ID_EVALUACIONChanged();
                }
            }
        }
        private global::System.Decimal _EXAMEN_ID_EVALUACION;
        partial void OnEXAMEN_ID_EVALUACIONChanging(global::System.Decimal value);
        partial void OnEXAMEN_ID_EVALUACIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DIAGNOSTICO
        {
            get
            {
                return _DIAGNOSTICO;
            }
            set
            {
                if (_DIAGNOSTICO != value)
                {
                    OnDIAGNOSTICOChanging(value);
                    ReportPropertyChanging("DIAGNOSTICO");
                    _DIAGNOSTICO = StructuralObject.SetValidValue(value, false, "DIAGNOSTICO");
                    ReportPropertyChanged("DIAGNOSTICO");
                    OnDIAGNOSTICOChanged();
                }
            }
        }
        private global::System.String _DIAGNOSTICO;
        partial void OnDIAGNOSTICOChanging(global::System.String value);
        partial void OnDIAGNOSTICOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_ATENCION
        {
            get
            {
                return _ID_ATENCION;
            }
            set
            {
                if (_ID_ATENCION != value)
                {
                    OnID_ATENCIONChanging(value);
                    ReportPropertyChanging("ID_ATENCION");
                    _ID_ATENCION = StructuralObject.SetValidValue(value, "ID_ATENCION");
                    ReportPropertyChanged("ID_ATENCION");
                    OnID_ATENCIONChanged();
                }
            }
        }
        private global::System.Decimal _ID_ATENCION;
        partial void OnID_ATENCIONChanging(global::System.Decimal value);
        partial void OnID_ATENCIONChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ATENCION_MEDICA_EXAMEN_FK", "EXAMEN")]
        public EXAMEN EXAMEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("Model.ATENCION_MEDICA_EXAMEN_FK", "EXAMEN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("Model.ATENCION_MEDICA_EXAMEN_FK", "EXAMEN").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EXAMEN> EXAMENReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EXAMEN>("Model.ATENCION_MEDICA_EXAMEN_FK", "EXAMEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EXAMEN>("Model.ATENCION_MEDICA_EXAMEN_FK", "EXAMEN", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ATENCION_MEDICA_MEDICO_FK", "MEDICO")]
        public MEDICO MEDICO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDICO>("Model.ATENCION_MEDICA_MEDICO_FK", "MEDICO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDICO>("Model.ATENCION_MEDICA_MEDICO_FK", "MEDICO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MEDICO> MEDICOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDICO>("Model.ATENCION_MEDICA_MEDICO_FK", "MEDICO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MEDICO>("Model.ATENCION_MEDICA_MEDICO_FK", "MEDICO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ATENCION_MEDICA_USUARIO_FK", "USUARIO")]
        public USUARIO USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("Model.ATENCION_MEDICA_USUARIO_FK", "USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("Model.ATENCION_MEDICA_USUARIO_FK", "USUARIO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIO> USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("Model.ATENCION_MEDICA_USUARIO_FK", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIO>("Model.ATENCION_MEDICA_USUARIO_FK", "USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CAPACITACION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CAPACITACION : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CAPACITACION.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="tIPO">Valor inicial de la propiedad TIPO.</param>
        /// <param name="lUGAR">Valor inicial de la propiedad LUGAR.</param>
        public static CAPACITACION CreateCAPACITACION(global::System.Decimal id, global::System.String tIPO, global::System.String lUGAR)
        {
            CAPACITACION cAPACITACION = new CAPACITACION();
            cAPACITACION.ID = id;
            cAPACITACION.TIPO = tIPO;
            cAPACITACION.LUGAR = lUGAR;
            return cAPACITACION;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, false, "TIPO");
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUGAR
        {
            get
            {
                return _LUGAR;
            }
            set
            {
                OnLUGARChanging(value);
                ReportPropertyChanging("LUGAR");
                _LUGAR = StructuralObject.SetValidValue(value, false, "LUGAR");
                ReportPropertyChanged("LUGAR");
                OnLUGARChanged();
            }
        }
        private global::System.String _LUGAR;
        partial void OnLUGARChanging(global::System.String value);
        partial void OnLUGARChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "US_CAP_CAPACITACION_FK", "US_CAP")]
        public EntityCollection<US_CAP> US_CAP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<US_CAP>("Model.US_CAP_CAPACITACION_FK", "US_CAP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<US_CAP>("Model.US_CAP_CAPACITACION_FK", "US_CAP", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EMPRESA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EMPRESA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EMPRESA.
        /// </summary>
        /// <param name="rUT_EMPRESA">Valor inicial de la propiedad RUT_EMPRESA.</param>
        /// <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
        /// <param name="dIRECCION">Valor inicial de la propiedad DIRECCION.</param>
        /// <param name="tELEFONO">Valor inicial de la propiedad TELEFONO.</param>
        /// <param name="eSTADO">Valor inicial de la propiedad ESTADO.</param>
        /// <param name="cONTRASEÑA">Valor inicial de la propiedad CONTRASEÑA.</param>
        public static EMPRESA CreateEMPRESA(global::System.String rUT_EMPRESA, global::System.String nOMBRE, global::System.String dIRECCION, global::System.Decimal tELEFONO, global::System.String eSTADO, global::System.String cONTRASEÑA)
        {
            EMPRESA eMPRESA = new EMPRESA();
            eMPRESA.RUT_EMPRESA = rUT_EMPRESA;
            eMPRESA.NOMBRE = nOMBRE;
            eMPRESA.DIRECCION = dIRECCION;
            eMPRESA.TELEFONO = tELEFONO;
            eMPRESA.ESTADO = eSTADO;
            eMPRESA.CONTRASEÑA = cONTRASEÑA;
            return eMPRESA;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_EMPRESA
        {
            get
            {
                return _RUT_EMPRESA;
            }
            set
            {
                if (_RUT_EMPRESA != value)
                {
                    OnRUT_EMPRESAChanging(value);
                    ReportPropertyChanging("RUT_EMPRESA");
                    _RUT_EMPRESA = StructuralObject.SetValidValue(value, false, "RUT_EMPRESA");
                    ReportPropertyChanged("RUT_EMPRESA");
                    OnRUT_EMPRESAChanged();
                }
            }
        }
        private global::System.String _RUT_EMPRESA;
        partial void OnRUT_EMPRESAChanging(global::System.String value);
        partial void OnRUT_EMPRESAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false, "NOMBRE");
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DIRECCION
        {
            get
            {
                return _DIRECCION;
            }
            set
            {
                OnDIRECCIONChanging(value);
                ReportPropertyChanging("DIRECCION");
                _DIRECCION = StructuralObject.SetValidValue(value, false, "DIRECCION");
                ReportPropertyChanged("DIRECCION");
                OnDIRECCIONChanged();
            }
        }
        private global::System.String _DIRECCION;
        partial void OnDIRECCIONChanging(global::System.String value);
        partial void OnDIRECCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TELEFONO
        {
            get
            {
                return _TELEFONO;
            }
            set
            {
                OnTELEFONOChanging(value);
                ReportPropertyChanging("TELEFONO");
                _TELEFONO = StructuralObject.SetValidValue(value, "TELEFONO");
                ReportPropertyChanged("TELEFONO");
                OnTELEFONOChanged();
            }
        }
        private global::System.Decimal _TELEFONO;
        partial void OnTELEFONOChanging(global::System.Decimal value);
        partial void OnTELEFONOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false, "ESTADO");
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONTRASEÑA
        {
            get
            {
                return _CONTRASEÑA;
            }
            set
            {
                OnCONTRASEÑAChanging(value);
                ReportPropertyChanging("CONTRASEÑA");
                _CONTRASEÑA = StructuralObject.SetValidValue(value, false, "CONTRASEÑA");
                ReportPropertyChanged("CONTRASEÑA");
                OnCONTRASEÑAChanged();
            }
        }
        private global::System.String _CONTRASEÑA;
        partial void OnCONTRASEÑAChanging(global::System.String value);
        partial void OnCONTRASEÑAChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EV_EMP_EMPRESA_FK", "EV_EMP")]
        public EntityCollection<EV_EMP> EV_EMP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EV_EMP>("Model.EV_EMP_EMPRESA_FK", "EV_EMP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EV_EMP>("Model.EV_EMP_EMPRESA_FK", "EV_EMP", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "USUARIO_EMPRESA_FK", "USUARIO")]
        public EntityCollection<USUARIO> USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIO>("Model.USUARIO_EMPRESA_FK", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIO>("Model.USUARIO_EMPRESA_FK", "USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EV_EMP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EV_EMP : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EV_EMP.
        /// </summary>
        /// <param name="fECHA">Valor inicial de la propiedad FECHA.</param>
        /// <param name="eVALUACION_ID">Valor inicial de la propiedad EVALUACION_ID.</param>
        /// <param name="eMPRESA_RUT_EMPRESA">Valor inicial de la propiedad EMPRESA_RUT_EMPRESA.</param>
        /// <param name="eSTADO_EV">Valor inicial de la propiedad ESTADO_EV.</param>
        /// <param name="iD_EV">Valor inicial de la propiedad ID_EV.</param>
        public static EV_EMP CreateEV_EMP(global::System.DateTime fECHA, global::System.Decimal eVALUACION_ID, global::System.String eMPRESA_RUT_EMPRESA, global::System.String eSTADO_EV, global::System.Decimal iD_EV)
        {
            EV_EMP eV_EMP = new EV_EMP();
            eV_EMP.FECHA = fECHA;
            eV_EMP.EVALUACION_ID = eVALUACION_ID;
            eV_EMP.EMPRESA_RUT_EMPRESA = eMPRESA_RUT_EMPRESA;
            eV_EMP.ESTADO_EV = eSTADO_EV;
            eV_EMP.ID_EV = iD_EV;
            return eV_EMP;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                OnFECHAChanging(value);
                ReportPropertyChanging("FECHA");
                _FECHA = StructuralObject.SetValidValue(value, "FECHA");
                ReportPropertyChanged("FECHA");
                OnFECHAChanged();
            }
        }
        private global::System.DateTime _FECHA;
        partial void OnFECHAChanging(global::System.DateTime value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EVALUACION_ID
        {
            get
            {
                return _EVALUACION_ID;
            }
            set
            {
                OnEVALUACION_IDChanging(value);
                ReportPropertyChanging("EVALUACION_ID");
                _EVALUACION_ID = StructuralObject.SetValidValue(value, "EVALUACION_ID");
                ReportPropertyChanged("EVALUACION_ID");
                OnEVALUACION_IDChanged();
            }
        }
        private global::System.Decimal _EVALUACION_ID;
        partial void OnEVALUACION_IDChanging(global::System.Decimal value);
        partial void OnEVALUACION_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMPRESA_RUT_EMPRESA
        {
            get
            {
                return _EMPRESA_RUT_EMPRESA;
            }
            set
            {
                OnEMPRESA_RUT_EMPRESAChanging(value);
                ReportPropertyChanging("EMPRESA_RUT_EMPRESA");
                _EMPRESA_RUT_EMPRESA = StructuralObject.SetValidValue(value, false, "EMPRESA_RUT_EMPRESA");
                ReportPropertyChanged("EMPRESA_RUT_EMPRESA");
                OnEMPRESA_RUT_EMPRESAChanged();
            }
        }
        private global::System.String _EMPRESA_RUT_EMPRESA;
        partial void OnEMPRESA_RUT_EMPRESAChanging(global::System.String value);
        partial void OnEMPRESA_RUT_EMPRESAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OBSERVACION_TECNICO
        {
            get
            {
                return _OBSERVACION_TECNICO;
            }
            set
            {
                OnOBSERVACION_TECNICOChanging(value);
                ReportPropertyChanging("OBSERVACION_TECNICO");
                _OBSERVACION_TECNICO = StructuralObject.SetValidValue(value, true, "OBSERVACION_TECNICO");
                ReportPropertyChanged("OBSERVACION_TECNICO");
                OnOBSERVACION_TECNICOChanged();
            }
        }
        private global::System.String _OBSERVACION_TECNICO;
        partial void OnOBSERVACION_TECNICOChanging(global::System.String value);
        partial void OnOBSERVACION_TECNICOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OBSERVACION_INGENIERO
        {
            get
            {
                return _OBSERVACION_INGENIERO;
            }
            set
            {
                OnOBSERVACION_INGENIEROChanging(value);
                ReportPropertyChanging("OBSERVACION_INGENIERO");
                _OBSERVACION_INGENIERO = StructuralObject.SetValidValue(value, true, "OBSERVACION_INGENIERO");
                ReportPropertyChanged("OBSERVACION_INGENIERO");
                OnOBSERVACION_INGENIEROChanged();
            }
        }
        private global::System.String _OBSERVACION_INGENIERO;
        partial void OnOBSERVACION_INGENIEROChanging(global::System.String value);
        partial void OnOBSERVACION_INGENIEROChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO_EV
        {
            get
            {
                return _ESTADO_EV;
            }
            set
            {
                OnESTADO_EVChanging(value);
                ReportPropertyChanging("ESTADO_EV");
                _ESTADO_EV = StructuralObject.SetValidValue(value, false, "ESTADO_EV");
                ReportPropertyChanged("ESTADO_EV");
                OnESTADO_EVChanged();
            }
        }
        private global::System.String _ESTADO_EV;
        partial void OnESTADO_EVChanging(global::System.String value);
        partial void OnESTADO_EVChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_EV
        {
            get
            {
                return _ID_EV;
            }
            set
            {
                if (_ID_EV != value)
                {
                    OnID_EVChanging(value);
                    ReportPropertyChanging("ID_EV");
                    _ID_EV = StructuralObject.SetValidValue(value, "ID_EV");
                    ReportPropertyChanged("ID_EV");
                    OnID_EVChanged();
                }
            }
        }
        private global::System.Decimal _ID_EV;
        partial void OnID_EVChanging(global::System.Decimal value);
        partial void OnID_EVChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EV_EMP_EMPRESA_FK", "EMPRESA")]
        public EMPRESA EMPRESA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPRESA>("Model.EV_EMP_EMPRESA_FK", "EMPRESA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPRESA>("Model.EV_EMP_EMPRESA_FK", "EMPRESA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EMPRESA> EMPRESAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPRESA>("Model.EV_EMP_EMPRESA_FK", "EMPRESA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EMPRESA>("Model.EV_EMP_EMPRESA_FK", "EMPRESA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EV_EMP_EVALUACION_FK", "EVALUACION")]
        public EVALUACION EVALUACION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EVALUACION>("Model.EV_EMP_EVALUACION_FK", "EVALUACION").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EVALUACION>("Model.EV_EMP_EVALUACION_FK", "EVALUACION").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EVALUACION> EVALUACIONReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EVALUACION>("Model.EV_EMP_EVALUACION_FK", "EVALUACION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EVALUACION>("Model.EV_EMP_EVALUACION_FK", "EVALUACION", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EVALUACION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EVALUACION : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EVALUACION.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        /// <param name="tIPO">Valor inicial de la propiedad TIPO.</param>
        /// <param name="eSTADO">Valor inicial de la propiedad ESTADO.</param>
        public static EVALUACION CreateEVALUACION(global::System.Decimal id, global::System.String tIPO, global::System.String eSTADO)
        {
            EVALUACION eVALUACION = new EVALUACION();
            eVALUACION.ID = id;
            eVALUACION.TIPO = tIPO;
            eVALUACION.ESTADO = eSTADO;
            return eVALUACION;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, false, "TIPO");
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false, "ESTADO");
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EV_EMP_EVALUACION_FK", "EV_EMP")]
        public EntityCollection<EV_EMP> EV_EMP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EV_EMP>("Model.EV_EMP_EVALUACION_FK", "EV_EMP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EV_EMP>("Model.EV_EMP_EVALUACION_FK", "EV_EMP", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EXAMEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EXAMEN : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EXAMEN.
        /// </summary>
        /// <param name="iD_EVALUACION">Valor inicial de la propiedad ID_EVALUACION.</param>
        /// <param name="tIPO">Valor inicial de la propiedad TIPO.</param>
        /// <param name="eSTADO">Valor inicial de la propiedad ESTADO.</param>
        public static EXAMEN CreateEXAMEN(global::System.Decimal iD_EVALUACION, global::System.String tIPO, global::System.String eSTADO)
        {
            EXAMEN eXAMEN = new EXAMEN();
            eXAMEN.ID_EVALUACION = iD_EVALUACION;
            eXAMEN.TIPO = tIPO;
            eXAMEN.ESTADO = eSTADO;
            return eXAMEN;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID_EVALUACION
        {
            get
            {
                return _ID_EVALUACION;
            }
            set
            {
                if (_ID_EVALUACION != value)
                {
                    OnID_EVALUACIONChanging(value);
                    ReportPropertyChanging("ID_EVALUACION");
                    _ID_EVALUACION = StructuralObject.SetValidValue(value, "ID_EVALUACION");
                    ReportPropertyChanged("ID_EVALUACION");
                    OnID_EVALUACIONChanged();
                }
            }
        }
        private global::System.Decimal _ID_EVALUACION;
        partial void OnID_EVALUACIONChanging(global::System.Decimal value);
        partial void OnID_EVALUACIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, false, "TIPO");
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false, "ESTADO");
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ATENCION_MEDICA_EXAMEN_FK", "ATENCION_MEDICA")]
        public EntityCollection<ATENCION_MEDICA> ATENCION_MEDICA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ATENCION_MEDICA>("Model.ATENCION_MEDICA_EXAMEN_FK", "ATENCION_MEDICA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ATENCION_MEDICA>("Model.ATENCION_MEDICA_EXAMEN_FK", "ATENCION_MEDICA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="MEDICO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MEDICO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto MEDICO.
        /// </summary>
        /// <param name="rUT_MEDICO">Valor inicial de la propiedad RUT_MEDICO.</param>
        /// <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
        /// <param name="aPELLIDO">Valor inicial de la propiedad APELLIDO.</param>
        /// <param name="eSPECIALIDAD">Valor inicial de la propiedad ESPECIALIDAD.</param>
        public static MEDICO CreateMEDICO(global::System.String rUT_MEDICO, global::System.String nOMBRE, global::System.String aPELLIDO, global::System.String eSPECIALIDAD)
        {
            MEDICO mEDICO = new MEDICO();
            mEDICO.RUT_MEDICO = rUT_MEDICO;
            mEDICO.NOMBRE = nOMBRE;
            mEDICO.APELLIDO = aPELLIDO;
            mEDICO.ESPECIALIDAD = eSPECIALIDAD;
            return mEDICO;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_MEDICO
        {
            get
            {
                return _RUT_MEDICO;
            }
            set
            {
                if (_RUT_MEDICO != value)
                {
                    OnRUT_MEDICOChanging(value);
                    ReportPropertyChanging("RUT_MEDICO");
                    _RUT_MEDICO = StructuralObject.SetValidValue(value, false, "RUT_MEDICO");
                    ReportPropertyChanged("RUT_MEDICO");
                    OnRUT_MEDICOChanged();
                }
            }
        }
        private global::System.String _RUT_MEDICO;
        partial void OnRUT_MEDICOChanging(global::System.String value);
        partial void OnRUT_MEDICOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false, "NOMBRE");
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String APELLIDO
        {
            get
            {
                return _APELLIDO;
            }
            set
            {
                OnAPELLIDOChanging(value);
                ReportPropertyChanging("APELLIDO");
                _APELLIDO = StructuralObject.SetValidValue(value, false, "APELLIDO");
                ReportPropertyChanged("APELLIDO");
                OnAPELLIDOChanged();
            }
        }
        private global::System.String _APELLIDO;
        partial void OnAPELLIDOChanging(global::System.String value);
        partial void OnAPELLIDOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESPECIALIDAD
        {
            get
            {
                return _ESPECIALIDAD;
            }
            set
            {
                OnESPECIALIDADChanging(value);
                ReportPropertyChanging("ESPECIALIDAD");
                _ESPECIALIDAD = StructuralObject.SetValidValue(value, false, "ESPECIALIDAD");
                ReportPropertyChanged("ESPECIALIDAD");
                OnESPECIALIDADChanged();
            }
        }
        private global::System.String _ESPECIALIDAD;
        partial void OnESPECIALIDADChanging(global::System.String value);
        partial void OnESPECIALIDADChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ATENCION_MEDICA_MEDICO_FK", "ATENCION_MEDICA")]
        public EntityCollection<ATENCION_MEDICA> ATENCION_MEDICA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ATENCION_MEDICA>("Model.ATENCION_MEDICA_MEDICO_FK", "ATENCION_MEDICA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ATENCION_MEDICA>("Model.ATENCION_MEDICA_MEDICO_FK", "ATENCION_MEDICA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="US_CAP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class US_CAP : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto US_CAP.
        /// </summary>
        /// <param name="uSUARIO_RUT">Valor inicial de la propiedad USUARIO_RUT.</param>
        /// <param name="fECHA">Valor inicial de la propiedad FECHA.</param>
        /// <param name="cAPACITACION_ID">Valor inicial de la propiedad CAPACITACION_ID.</param>
        /// <param name="oBSERVACION">Valor inicial de la propiedad OBSERVACION.</param>
        public static US_CAP CreateUS_CAP(global::System.String uSUARIO_RUT, global::System.DateTime fECHA, global::System.Decimal cAPACITACION_ID, global::System.String oBSERVACION)
        {
            US_CAP uS_CAP = new US_CAP();
            uS_CAP.USUARIO_RUT = uSUARIO_RUT;
            uS_CAP.FECHA = fECHA;
            uS_CAP.CAPACITACION_ID = cAPACITACION_ID;
            uS_CAP.OBSERVACION = oBSERVACION;
            return uS_CAP;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO_RUT
        {
            get
            {
                return _USUARIO_RUT;
            }
            set
            {
                if (_USUARIO_RUT != value)
                {
                    OnUSUARIO_RUTChanging(value);
                    ReportPropertyChanging("USUARIO_RUT");
                    _USUARIO_RUT = StructuralObject.SetValidValue(value, false, "USUARIO_RUT");
                    ReportPropertyChanged("USUARIO_RUT");
                    OnUSUARIO_RUTChanged();
                }
            }
        }
        private global::System.String _USUARIO_RUT;
        partial void OnUSUARIO_RUTChanging(global::System.String value);
        partial void OnUSUARIO_RUTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA
        {
            get
            {
                return _FECHA;
            }
            set
            {
                if (_FECHA != value)
                {
                    OnFECHAChanging(value);
                    ReportPropertyChanging("FECHA");
                    _FECHA = StructuralObject.SetValidValue(value, "FECHA");
                    ReportPropertyChanged("FECHA");
                    OnFECHAChanged();
                }
            }
        }
        private global::System.DateTime _FECHA;
        partial void OnFECHAChanging(global::System.DateTime value);
        partial void OnFECHAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CAPACITACION_ID
        {
            get
            {
                return _CAPACITACION_ID;
            }
            set
            {
                if (_CAPACITACION_ID != value)
                {
                    OnCAPACITACION_IDChanging(value);
                    ReportPropertyChanging("CAPACITACION_ID");
                    _CAPACITACION_ID = StructuralObject.SetValidValue(value, "CAPACITACION_ID");
                    ReportPropertyChanged("CAPACITACION_ID");
                    OnCAPACITACION_IDChanged();
                }
            }
        }
        private global::System.Decimal _CAPACITACION_ID;
        partial void OnCAPACITACION_IDChanging(global::System.Decimal value);
        partial void OnCAPACITACION_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OBSERVACION
        {
            get
            {
                return _OBSERVACION;
            }
            set
            {
                if (_OBSERVACION != value)
                {
                    OnOBSERVACIONChanging(value);
                    ReportPropertyChanging("OBSERVACION");
                    _OBSERVACION = StructuralObject.SetValidValue(value, false, "OBSERVACION");
                    ReportPropertyChanged("OBSERVACION");
                    OnOBSERVACIONChanged();
                }
            }
        }
        private global::System.String _OBSERVACION;
        partial void OnOBSERVACIONChanging(global::System.String value);
        partial void OnOBSERVACIONChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "US_CAP_CAPACITACION_FK", "CAPACITACION")]
        public CAPACITACION CAPACITACION
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CAPACITACION>("Model.US_CAP_CAPACITACION_FK", "CAPACITACION").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CAPACITACION>("Model.US_CAP_CAPACITACION_FK", "CAPACITACION").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CAPACITACION> CAPACITACIONReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CAPACITACION>("Model.US_CAP_CAPACITACION_FK", "CAPACITACION");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CAPACITACION>("Model.US_CAP_CAPACITACION_FK", "CAPACITACION", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "US_CAP_USUARIO_FK", "USUARIO")]
        public USUARIO USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("Model.US_CAP_USUARIO_FK", "USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("Model.US_CAP_USUARIO_FK", "USUARIO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<USUARIO> USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<USUARIO>("Model.US_CAP_USUARIO_FK", "USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<USUARIO>("Model.US_CAP_USUARIO_FK", "USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto USUARIO.
        /// </summary>
        /// <param name="rUT">Valor inicial de la propiedad RUT.</param>
        /// <param name="tIPO">Valor inicial de la propiedad TIPO.</param>
        /// <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
        /// <param name="aPELLIDO">Valor inicial de la propiedad APELLIDO.</param>
        /// <param name="cONTRASEÑA">Valor inicial de la propiedad CONTRASEÑA.</param>
        /// <param name="eSTADO">Valor inicial de la propiedad ESTADO.</param>
        /// <param name="eMPRESA_RUT_EMPRESA">Valor inicial de la propiedad EMPRESA_RUT_EMPRESA.</param>
        public static USUARIO CreateUSUARIO(global::System.String rUT, global::System.String tIPO, global::System.String nOMBRE, global::System.String aPELLIDO, global::System.String cONTRASEÑA, global::System.String eSTADO, global::System.String eMPRESA_RUT_EMPRESA)
        {
            USUARIO uSUARIO = new USUARIO();
            uSUARIO.RUT = rUT;
            uSUARIO.TIPO = tIPO;
            uSUARIO.NOMBRE = nOMBRE;
            uSUARIO.APELLIDO = aPELLIDO;
            uSUARIO.CONTRASEÑA = cONTRASEÑA;
            uSUARIO.ESTADO = eSTADO;
            uSUARIO.EMPRESA_RUT_EMPRESA = eMPRESA_RUT_EMPRESA;
            return uSUARIO;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT
        {
            get
            {
                return _RUT;
            }
            set
            {
                if (_RUT != value)
                {
                    OnRUTChanging(value);
                    ReportPropertyChanging("RUT");
                    _RUT = StructuralObject.SetValidValue(value, false, "RUT");
                    ReportPropertyChanged("RUT");
                    OnRUTChanged();
                }
            }
        }
        private global::System.String _RUT;
        partial void OnRUTChanging(global::System.String value);
        partial void OnRUTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, false, "TIPO");
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE
        {
            get
            {
                return _NOMBRE;
            }
            set
            {
                OnNOMBREChanging(value);
                ReportPropertyChanging("NOMBRE");
                _NOMBRE = StructuralObject.SetValidValue(value, false, "NOMBRE");
                ReportPropertyChanged("NOMBRE");
                OnNOMBREChanged();
            }
        }
        private global::System.String _NOMBRE;
        partial void OnNOMBREChanging(global::System.String value);
        partial void OnNOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String APELLIDO
        {
            get
            {
                return _APELLIDO;
            }
            set
            {
                OnAPELLIDOChanging(value);
                ReportPropertyChanging("APELLIDO");
                _APELLIDO = StructuralObject.SetValidValue(value, false, "APELLIDO");
                ReportPropertyChanged("APELLIDO");
                OnAPELLIDOChanged();
            }
        }
        private global::System.String _APELLIDO;
        partial void OnAPELLIDOChanging(global::System.String value);
        partial void OnAPELLIDOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONTRASEÑA
        {
            get
            {
                return _CONTRASEÑA;
            }
            set
            {
                OnCONTRASEÑAChanging(value);
                ReportPropertyChanging("CONTRASEÑA");
                _CONTRASEÑA = StructuralObject.SetValidValue(value, false, "CONTRASEÑA");
                ReportPropertyChanged("CONTRASEÑA");
                OnCONTRASEÑAChanged();
            }
        }
        private global::System.String _CONTRASEÑA;
        partial void OnCONTRASEÑAChanging(global::System.String value);
        partial void OnCONTRASEÑAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false, "ESTADO");
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMPRESA_RUT_EMPRESA
        {
            get
            {
                return _EMPRESA_RUT_EMPRESA;
            }
            set
            {
                OnEMPRESA_RUT_EMPRESAChanging(value);
                ReportPropertyChanging("EMPRESA_RUT_EMPRESA");
                _EMPRESA_RUT_EMPRESA = StructuralObject.SetValidValue(value, false, "EMPRESA_RUT_EMPRESA");
                ReportPropertyChanged("EMPRESA_RUT_EMPRESA");
                OnEMPRESA_RUT_EMPRESAChanged();
            }
        }
        private global::System.String _EMPRESA_RUT_EMPRESA;
        partial void OnEMPRESA_RUT_EMPRESAChanging(global::System.String value);
        partial void OnEMPRESA_RUT_EMPRESAChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "USUARIO_EMPRESA_FK", "EMPRESA")]
        public EMPRESA EMPRESA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPRESA>("Model.USUARIO_EMPRESA_FK", "EMPRESA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPRESA>("Model.USUARIO_EMPRESA_FK", "EMPRESA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EMPRESA> EMPRESAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EMPRESA>("Model.USUARIO_EMPRESA_FK", "EMPRESA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EMPRESA>("Model.USUARIO_EMPRESA_FK", "EMPRESA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ATENCION_MEDICA_USUARIO_FK", "ATENCION_MEDICA")]
        public EntityCollection<ATENCION_MEDICA> ATENCION_MEDICA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ATENCION_MEDICA>("Model.ATENCION_MEDICA_USUARIO_FK", "ATENCION_MEDICA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ATENCION_MEDICA>("Model.ATENCION_MEDICA_USUARIO_FK", "ATENCION_MEDICA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "US_CAP_USUARIO_FK", "US_CAP")]
        public EntityCollection<US_CAP> US_CAP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<US_CAP>("Model.US_CAP_USUARIO_FK", "US_CAP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<US_CAP>("Model.US_CAP_USUARIO_FK", "US_CAP", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
