//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ATENCION_MEDICA = new HashSet<ATENCION_MEDICA>();
            this.US_CAP = new HashSet<US_CAP>();
        }
    
        public string RUT { get; set; }
        public string TIPO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string ESTADO { get; set; }
        public string EMPRESA_RUT_EMPRESA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<ATENCION_MEDICA> ATENCION_MEDICA { get; set; }
        public virtual ICollection<US_CAP> US_CAP { get; set; }
    }
}
